### ISSUE TITLE
This code is valid only k=1. I think

### ISSUE THREAD

**Issue by ARUN62** [lkawka/3d-nearest-neighbor-search-in-kd-tree-cuda#1]
Please help me to understand this code snippets.  If I am changing k=5,10,15,20 and so on. 

If I am not correct please suggest me. what line focusing k value..

**Comment by lkawka** [comment]
It was a university task, and it asked for implementation only for k=3, hence 3d in the title.

**Comment by ARUN62** [comment]
Actually, I am asking K= number of nearest data points. For Example- input: Random Query generated (X,Y,Z) point
Output : K=1 only one closest point is given w.r.t of query point, shortest distance of point and time elapsed.

So, If  I am changing K=5,10,15,20 and so on. For Example- input: Random Query generated (X,Y,Z) point ans set K=5
Output: 5 closest point is given w.r.t of query point,  5 shortest distance of each point and time elapsed of whole process.

Finally, I think get it my point so, what changes required this code snippet, please suggest me.

**Comment by lkawka** [comment]
I can't think of any easy way to modify this code to find k nearest neighbours. I'm afraid I won't be able to help you.
