### ISSUE TITLE
This code is valid only random points 

### ISSUE THREAD

**Issue by ARUN62** [lkawka/3d-nearest-neighbor-search-in-kd-tree-cuda#2]
This code is giving accurate result only random points.  Are you sure about that. Because I am passing hard input points its gives wrong results. That's why I am asking.

Code:

#include <iostream>
#include <bits/stdc++.h>
#include <chrono> 
#include <algorithm>
#include <math.h> 
using namespace std;

const int N_POINTS = 9, N_QUERIES = 1, INF = 1e9, RANGE_MAX = 100, N_PRINT = 1;

struct int3D
{
    int x;
    int y;
    int z;
};

void print(int3D *points, int n);
void generatePoints(int3D *points, int n);
void buildKDTree(int3D *points, int3D *tree, int n, int m);
int3D findNearestNeighbor(int3D *tree, int treeSize, int treeNode, int depth, int3D query);
void printResults(int3D *queries, int3D *results, int n);

int main()
{

    int TREE_SIZE = 1;
    while (TREE_SIZE < N_POINTS)
        TREE_SIZE <<=1;

    int3D *points = new int3D[N_POINTS];
    int3D *tree = new int3D[TREE_SIZE];
    int3D *queries = new int3D[N_QUERIES];

    points[0] = {12, 2, 42};
    points[1] = {13, 22, 4};
    points[2] = {12, 2, 44};
    points[3] = {1, 24, 44};
    points[4] = {12, 22, 4};
    points[5] = {1, 22, 42};
    points[6] = {1, 21, 41};
    points[7] = {1, 23, 40};
    points[8] = {11, 21, 4};

    // generatePoints(points, N_POINTS);
    buildKDTree(points, tree, N_POINTS, TREE_SIZE);
    // generatePoints(queries, N_QUERIES);
    
    queries[0] = {12, 21, 5};

    auto start = std::chrono::system_clock::now();

    int3D *results = new int3D[N_QUERIES];
    for (int i = 0; i < N_QUERIES; i++)
    {
        results[i] = findNearestNeighbor(tree, TREE_SIZE, 1, 0, queries[i]);
        vector<vector<int>>vi;
    }

    auto end = std::chrono::system_clock::now();
    float duration = 1000.0 * std::chrono::duration<float>(end - start).count();

    printResults(queries, results, N_PRINT);
    std::cout << "Elapsed time in milliseconds : " << duration << "ms\n\n";
}

void print(int3D *points, int n)
{
    for (int i = 0; i < n; i++)
    {
        std::cout << "[" << points[i].x << "," << points[i].y << ", " << points[i].z << "] ";
    }
    std::cout << std::endl;
}

void generatePoints(int3D *points, int n)
{
    // for (int i = 0; i < n; i++)
    // {
    //     points[i] = {.x = rand() % RANGE_MAX+1, .y = rand() % RANGE_MAX+1, .z = rand() % RANGE_MAX+1};
    // }
    
}

int3D closer(int3D p, int3D p2, int3D p3)
{
    if ((abs(p.x - p2.x) + abs(p.y - p2.y) + abs(p.z - p2.z)) < (abs(p.x - p3.x) + abs(p.y - p3.y) + abs(p.z - p3.z)))
    {
        return p2;
    }
    return p3;
}

void buildSubTree(int3D *points, int3D *tree, int start, int end, int depth, int node)
{
    if (start >= end)
    {
        return;
    }

    std::sort(points + start, points + end, [depth](int3D p1, int3D p2) -> bool {
        if (depth % 3 == 0)
            return p1.x < p2.x;
        if (depth % 3 == 1)
            return p1.y < p2.y;
        return p1.z < p2.z;
    });

    int split = (start + end - 1) / 2;

    tree[node] = points[split];

    buildSubTree(points, tree, start, split, depth + 1, node * 2);
    buildSubTree(points, tree, split + 1, end, depth + 1, node * 2 + 1);
}

void buildKDTree(int3D *points, int3D *tree, int n, int treeSize)
{
    for (int i = 0; i < treeSize; i++)
    {
        tree[i] = {.x = INF, .y = -INF, .z = -INF};
    }

    buildSubTree(points, tree, 0, n, 0, 1);
}

int3D findNearestNeighbor(int3D *tree, int treeSize, int treeNode, int depth, int3D query)
{
    int3D node = tree[treeNode];

    int val1, val2;
    if (depth % 3 == 0)
    {
        val1 = node.x;
        val2 = query.x;
    }
    else if (depth % 3 == 1)
    {
        val1 = node.y;
        val2 = query.y;
    }
    else
    {
        val1 = node.z;
        val2 = query.z;
    }

    if ((val1 < val2) && (treeNode * 2 < treeSize))
    {
        int3D leftChild = tree[treeNode * 2];
        if (leftChild.x != -INF && leftChild.y != -INF && leftChild.z != -INF)
        {
            return closer(query, node, findNearestNeighbor(tree, treeSize, treeNode * 2, depth + 1, query));
        }
    }
    else if ((val1 > val2) && (treeNode * 2 + 1 < treeSize))
    {
        int3D rightChild = tree[treeNode * 2 + 1];
        if (rightChild.x != -INF && rightChild.y != -INF && rightChild.z != -INF)
        {
            return closer(query, node, findNearestNeighbor(tree, treeSize, treeNode * 2 + 1, depth + 1, query));
        }
    }
    return node;
}

void printResults(int3D *queries, int3D *results, int n) {
    for(int i = 0; i < n; i++) {
        std::cout<<"query: ["<<queries[i].x<<", "<<queries[i].y<<", "<<queries[i].z<<"] ";
        std::cout<<", result: ["<<results[i].x<<", "<<results[i].y<<", "<<results[i].z<<"] ";
        std::cout<<", distance: "<<sqrt(pow(queries[i].x - results[i].x, 2) + pow(queries[i].y - results[i].y, 2) + pow(queries[i].z - results[i].z, 2));
        std::cout<<std::endl;
    }
}

Disclaimer:

Correct output is "(12, 22, 4)"
but its given is "(11, 21, 4)"

Please check it out & help me.

**Comment by lkawka** [comment]
So this is an approximation, not an exact algorithm.
